image: Visual Studio 2017
shallow_clone: true

branches:
  only:
    - master
    - production

platform: x64

configuration: Release

test: off

matrix:
  fast_finish: true

cache:
 - c:\tools\vcpkg\installed\


before_build:
  - cmd: >-
    git clone https://github.com/Vasar007/TIMLE.git

    cd SFML

    mkdir install

    mkdir build

    cd build

    cmake .. -DCMAKE_INSTALL_PREFIX=../install -DSFML_DEPENDENCIES_INSTALL_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE

    msbuild INSTALL.vcxproj

    cd ../../

    git clone https://github.com/Vasar007/TIMLE.git

    cd TIMLE

    mkdir build

    mkdir build/TIMLE

    cmake . -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_INSTALL_PREFIX=./build/TIMLE -DCMAKE_PREFIX_PATH=./SFML/install

build:
  project: TIMLE/build/INSTALL.vcxproj
  parallel: true
  verbosity: minimal
