image: Visual Studio 2017
shallow_clone: true

branches:
  only:
    - master
    - production

platform:
  - x64

configuration:
  - Release

test: off

matrix:
  fast_finish: true

cache:
 - c:\tools\vcpkg\installed\


before_build:
  - cmd: .appveyor\install.cmd

build:
  project: TIMLE/build/INSTALL.vcxproj
  parallel: true
  verbosity: minimal
